// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkvicbubpswhqvroezre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdmljYnVicHN3aHF2cm9lenJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTEyNTUsImV4cCI6MjA1NTUyNzI1NX0.YuXkEARdRthtgd9Iqt-TkAz4R8siQPtetsRm7x2ZDBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Debug információk a konzolra
console.log('Supabase kliens inicializálva:', {
  url: SUPABASE_URL,
  realtime: true,
  eventsPerSecond: 10
});